### PR TITLE
Update app icon

### PR DESCRIPTION
**Pull request by daudix-UFO**
Same idea, different icons and colors

Alternative variants:
me dusansimic DynamicWallpaper Devel
me dusansimic DynamicWallpaper
me dusansimic DynamicWallpaper svg1 Devel
me dusansimic DynamicWallpaper svg1
me dusansimic DynamicWallpaper svg2 Devel
me dusansimic DynamicWallpaper svg2

Old icon, but now it follows GNOME HIG

me dusansimic DynamicWallpaper svg3 Devel
me dusansimic DynamicWallpaper svg3

All icons zip:
[me.dusansimic.DynamicWallpaper.zip](https://github.com/dusansimic/dynamic-wallpaper/files/8884535/me.dusansimic.DynamicWallpaper.zip)

### CODE REVIEW

**Comment by daudix-UFO** [comment]
@dusansimic Well, what do they look like?

**Comment by dusansimic** [comment]
Sorry for the delayed response. I personally prefer the old icon, it's very minimal and fits nicely on the desktop. I will add the nightly variant of the icon you've made tho, thanks for that! I've been thinking about making one myself but you were faster :smile:.

Could you add add it as `me.dusansimic.DynamicWallpaper.Devel.svg` in the icons directory?

**Comment by daudix-UFO** [comment]
Ok, no problem, but how about fixed old one? (latest in list)

**Comment by daudix-UFO** [comment]
Added "fixed old icon" and nightly variant ;), you can see differences on "Files changed" section

**Comment by dusansimic** [comment]
What exactly was changed? After inspecting it more closely it seems like you've changed the aspect ration and added some padding. Is that what you meant by following gnome hig?

**Comment by daudix-UFO** [comment]
Yes, icons need to follow special shape, old one just not followed shape guides

_Here is what I talking about:_

Снимок экрана от 2022-06-19 17-43-07

**Comment by dusansimic** [comment]
I see now. I think that is what was already done by Rokwallaby (the icon creator) but I've in my infinite wisdom decided that it didn't look quite right and modified it a bit 😅.

> If you want, you can keep current one, it just a suggestion
No need, I'd like to follow Gnome HIG as much as possible.

Thanks for the fixes!

**Comment by daudix-UFO** [comment]
And thank you for understanding :)

**Pull request merged**
